### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by paxpistor** [paxpistor/JavaCourse#1]
Create your HTML page.

**Comment by 1monusingh** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    This is body of the page 
</body>
`</html>```

**Comment by 1monusingh** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    This is body of the page 
</body>
</html>
